### PR TITLE
[WIP] Modernize the codebase

### PR DESCRIPTION
**Pull request by xvrc**
Right now, this is only the result of my attempt to get Stunt Rally to build with Visual Studio 2019 using C++17, plus a few changes here and there.

I was primarily motivated by the fact that the last Windows binaries were compiled with Visual Studio 2010, and that
building this project on Windows requires a fair amount of patience (if also building the dependencies), as detailed in the Wiki.
In addition to some source code fixes, I ended up modifying the build script quite a bit to get everything working.

A quick overview of the changes:
 - **removed some FindXXX CMake modules.** Except for MyGUI script, all the removed modules were incorporated into CMake's distribution (at least as of CMake 3.16, the new minimum version), so they didn't need to be part of the source tree anymore.
 - **updated handling of dependencies.** In particular, Bullet now no longer needs to be found with BulletFileLoader/BulletWorldImporter since those components are part of the source tree. I also simply dropped support for detection and handling of OGRE 1.9 and below. Finally, MyGUI has been added directly to the source tree (although I wonder if there shouldn't be some override to allow using the system package)
 - **automatically generated PCHs** via CMake
 - **enforced use of C++17** (see below)
 - **converted the README into markdown format**

Here's how the build process on Windows looks like now:
1. Install Visual Studio 2019 (with the C/C++ dev package, of course). You could also just download the MS build tools + CMake and work from there, but I haven't tried.
2. Install [vcpkg](https://github.com/microsoft/vcpkg).
3. Clone the repository: `git clone --single-branch --branch modernize https://github.com/xvrc/stuntrally.git`
4. Inside the repository, run `cmake -B build -S . -G"Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=<path to vcpkg root>/scripts/buildsystems/vcpkg.cmake` (might need to open a Visual Studio Developer Command Prompt for CMake)
5. Open the solution file in the build folder, and build it.
6. All done! The game's exe is in `build/bin/`.

Now, to run the new build will require a bit of manual setup at the moment:
1. Copy `data/` and `config/` into `bin/`
2. Get a copy of the tracks and put that in `bin/data/`.
3. Copy the `MyGUI_Ogre_XX.*` files (located at `extern/mygui/MyGUI_Media/`) into `bin/data/gui/` (or some subfolder of `bin/data/`, as long as they can be found via OGRE resources).
4. Copy the necessary OGRE plugins (Codec, GL render system, etc.), which are located at `build/vcpkg_installed/<triplet>/bin/` for non-debug builds
   and `build/vcpkg_installed/<triplet>/debug/bin/` for debug builds, next to the game executable (note: I commented out usage of the D3D9 plugin as it isn't built by default; see below for more info)
5. Start the game (and hopefully I didn't miss a step)

I eventually plan to remove these pre-run steps entirely via CMake.

This PR is far from complete:
 - I would like to expand on the use of C++17 throughout the codebase, to the point that the dependency on Boost can be removed entirely, because that thing is just suuuuupppperrrr big and mostly just duplicates a lot of stuff which already exists in the standard library.
 - The CMake build script is still very messy: all the libraries are just bunched together and injected into every target...
 - The game is very unstable right now with the updated dependencies brought in by vcpkg (OGRE on vcpkg is on version 1.12.9). For instance, I don't know if it's a graphics card issue, but there are no colors when playing a track on my end (everything that isn't part of the UI is some shade of white).
   And that's if you even manage to load a track; sometimes a random assert is triggered during loading.
 - Code should be updated to reflect features of dependencies (e.g. the D3D9 plugin, although available as a "feature", isn't built by default with vcpkg - and really, I don't think dropping it entirely will be much of an issue).
 - Maybe add a clang-format file?

I'm hoping to get some feedback first before trying anything else.

Finally, I just want to say that this game is a lot of fun! I enjoyed exploring the diverse set of tracks with all the different vehicles.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Cool! Could you please also test if it fixes #29? :-)

**Comment by cryham** [comment]
Quite interesting. I didn't know about vcpkg.
I'm curious how far this PR could go.

I'd prefer if this didn't have so many changes at once though. Would be easier to merge someday. E.g. README really has nothing to do with this, it could be a separate PR, where I'd ask if you also changed game's code reading this file to display it in Gui: Help - Readme tab.

I do like the move to new C++ and removing Boost.
I just have to say here that Ogre 1.12 PR isn't really done and working with SR still. (I think I'd be happier moving to 2.2 but it's way more effort).
"some shade of white" - I'm guessing shaders aren't working, or had errors.
"game is very unstable" - well this is a bad sign, isn't it.

I don't know how is this supposed to still work on e.g. Debian where I just get every dependency using apt-get and don't want to use vcpkg. Perhaps vcpkg gives access to newer Ogre though. Is Ogre 2.2 in it too?
Does vcpkg set global paths or something? So does it destroy building any other project on same PC? What if I wanted to build SR with Ogre 1.9, and this PR on Debian on same PC?

**Comment by xvrc** [comment]
@AsciiWolf unfortunately, I get the exact same backtrace from the original issue, so no changes there. If I can, I'll try to debug this further.

@cryham:

> README really has nothing to do with this, it could be a separate PR, where I'd ask if you also changed game's code reading this file to display it in Gui: Help - Readme tab.

Whoops. I didn't even know that file was part of a GUI tab. I'll revert that.

> "some shade or white" - I'm guessing shaders aren't working, or had errors.

Looking at the logs, while I had made the game load the GL rendersystem instead of the D3D9 rendersystem, it seems the engine thought it could compile D3D shaders...?

In `ogre.err`, I see stuff like:
```
Failed to compile shader "shadowcaster_vertex_16957637337227343065". Consider the OGRE log for more information.
        Full source code below: 


void main(                   float4 iPosition : POSITION                 , out float4 oPosition : POSITION
        
, in float2  uv0 : TEXCOORD0
        , out float2  UV : TEXCOORD0
        
, uniform float4x4  wvp  
        , out float2  depth : TEXCOORD1

    )
    {
			
			
oPosition = mul(wvp,  iPosition);

	    
	    depth.x = oPosition.z;
	    depth.y = oPosition.w;

	    
	    oPosition.z = max(oPosition.z, 0);

	    
UV = uv0;
    }
```  
but in `ogre.log`,
```
RenderSystem Name: OpenGL Rendering Subsystem
```
is reported.

> "game is very unstable" - well this is a bad sign, isn't it.

Well, it's mostly assertions being triggered, some having to do with physics logic, other times with terrain, almost at random. I'd have to play around a bit more to see under what circumstances these things happen.

> I don't know how is this supposed to still work on e.g. Debian where I just get every dependency using apt-get and don't want to use vcpkg.

You shouldn't need to change anything for non-Windows platforms at all; all vcpkg does, when added to the CMake command (the `-DCMAKE_TOOLCHAIN_FILE=...` part), is add paths to the libraries it built (which are put inside the build folder) for package-finding scripts to use. It won't do anything otherwise. You could just not specify it and `find_package()` will work like before.

You could probably even have a hybrid setup (i.e. install only some packages through vcpkg) where packages are found through the system as a fallback, but I don't think that's practical.

Note that you can use vcpkg as an alternate package manager, by adding `vcpkg` to the PATH, and doing `vcpkg install <whatever>`. It'll put built libraries into a subfolder where vcpkg is installed. This also won't override system packages unless you tell it to via the CMake command.

> Does vcpkg set global paths or something? So does it destroy building any other project on same PC? What if I wanted to build SR with Ogre 1.9, and this PR on Debian on same PC (or on Windows if I had other projects present)?

See above.

> Perhaps vcpkg gives access to newer Ogre though. Is Ogre 2.2 in it too?

Well, `ogre-next` is listed in vcpkg, but I don't think it corresponds to the latest Ogre 2.2; its version tag says `2019-10-20`, so I'll assume it's some commit from 2019.

> SR code is written in my very specific way, any auto format would just destroy it.

Got it. Does that mean that for any C++ changes, I should just write in some style as close as existing code as possible, or it just doesn't matter?

**Comment by cryham** [comment]
> Looking at the logs, while I had made the game load the GL rendersystem instead of the D3D9 rendersystem, it seems the engine thought it could compile D3D shaders...?

Wait, if I remember this right, GL didn't work on Windows. I think I didn't want to bother with that and fixed SR to use D3D9/11 on Windows.

> Failed to compile shader "shadowcaster_vertex_16957637337227343065". Consider the OGRE log for more information.
Yeah that's why its white shaded.

> Well, it's mostly assertions being triggered, 
I'm not sure if I tested any asserts during Debug, was a long time ago, but surely nothing crashed in Release build.

> You shouldn't need to change anything for non-Windows platforms at all; 
That's good.

> Got it. Does that mean that for any C++ changes, I should just write in some style as close as existing code as possible, or it just doesn't matter?
Yeah, that'd be great if you did. But if too much trouble just write in your style.

**Comment by xvrc** [comment]
Alright, I got it to build with Ogre's D3D9 RenderSystem and indeed all the graphics work properly now. The problem with this is that the D3DX9 utility library doesn't come with the newer Windows 10 SDK, and the D3D9 RenderSystem tries to link to that particular library when building Ogre from vcpkg. So I had to manually move some files around to get this setup to work.

I did try to use the D3D11 RenderSystem instead, but I got this error dialog when I loaded a track:

image

Instead of chasing after stuff like this, what I can (and probably should) do is:
1. split out the changes regarding vcpkg integration into a separate PR, as it works. This would enable building on Windows *almost* as seamlessly as I described originally, with the exception of the D3DX9 workaround I had to do. This won't include the C++17 changes, though there will be some code modifications because of the updated dependencies coming from vcpkg.
2. make a new PR which updates the PCH logic, using CMake's new functionality.
3. make another PR with the changes needed to get the code to compile with C++17.
4. finally get to updating the rendering code so that it doesn't require D3D9 as the rendering backend on Windows anymore.

**Comment by cryham** [comment]
Right this sounds like a very good plan.

I'm not sure if DX11 works. Was at some point developed but as far as I remember DX11 didn't improve much (it's still older Ogre architecture). And GL on Windows in Ogre even had bit less Fps so that's why DX9 was main default. This is old history, now it'd be better to use Ogre 1.12 or Ogre 2.3 to get more Fps and performance.

**Pull request closed without merging**
