### PR TITLE
new and reworked obstacles added

### PR DESCRIPTION
**Pull request by rubberduck9999**
before adding these, note that I added a directory called "_obstacles_sources_and_png". I added the blend file there, and the original png version, for the game you may want to leave the textures as jpg to save space and resources, move them to the blend_files repo to save the space here, as the textures are already 2K.

and 2. I needed to locally comment one line out of the .gitignore, but i think is is generally a bit confusing, there is objects, objects0, 2 and C. SO I moved them to objects2, but when I still wasn't able to add these, I checked the file

### CODE REVIEW

**Comment by cryham** [comment]
Okay could you remove _obstacles_sources_and_png directory from here and add it there:
https://github.com/stuntrally/blendfiles/tree/master/props
Which is the repo for such big png files and blend files too. Size doesn't matter there, and for game this is not needed and would only add more MB.

**Comment by rubberduck9999** [comment]
ok, no problem

**Comment by cryham** [comment]
Okay I'll commit this myself without _obstacles_sources_and_png

**Comment by cryham** [comment]
Ok done. So I'm closing this PR.
Can you tell which license I should put in readme2.txt for these?

**Comment by rubberduck9999** [comment]
they are all cc0 too

**Pull request closed without merging**
