### PR TITLE
fix stuttering and add ogre 13 support

### LINKED ISSUE #31: Lot of stuttering during gameplay (paged-geom vegetation lags)
When using latest Stunt Rally from Git with OGRE 1.12.10, there seems to be lot of stuttering during the gameplay. It seems to probably be caused by vegetation models because it does not happen on maps with minimal vegetation. If I remember correctly, there was no such issue with older Stunt Rally / older OGRE.

### PR DESCRIPTION
**Pull request by paroj**
first commit should fix #31. [click here to ignore the EOL changes](https://github.com/stuntrally/stuntrally/pull/43/commits/6d11cef4720e96c1bc70a6d41b9f745a8dfce533?diff=unified&w=1)

second commit adds ogre 13 support.

this can be tested via:
```
sudo snap install stuntrally --edge
```

### CODE REVIEW

**Comment by cryham** [comment]
So I tried:
`sudo snap install stuntrally --edge`
It ended rather quickly
then `snap run stuntrally`
Any idea what happens or what am I doing wrong? It's been a while, sorry if something trivial.
```
root@debian:/home/ch/dn# snap install stuntrally --edge     
stuntrally (edge) 2.6.1+ogre13 from Pavel Rojtberg (paroj) installed
root@debian:/home/ch/dn# snap
The snap command lets you install, configure, refresh and remove snaps.
Snaps are packages that work across many different Linux distributions,
enabling secure delivery and operation of the latest apps and utilities.

Usage: snap <command> [<options>...]

Commands can be classified as follows:

         Basics: find, info, install, list, remove
        ...more: refresh, revert, switch, disable, enable
        History: changes, tasks, abort, watch
        Daemons: services, start, stop, restart, logs
       Commands: alias, aliases, unalias, prefer
  Configuration: get, set, wait
        Account: login, logout, whoami
    Permissions: interfaces, interface, connect, disconnect
      Snapshots: saved, save, check-snapshot, restore, forget
          Other: version, warnings, okay
    Development: run, pack, try, ack, known, download

For more information about a command, run 'snap help <command>'.
For a short summary of all commands, run 'snap help --all'.
root@debian:/home/ch/dn# snap run stuntrally
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
Creating resource group General
Creating resource group OgreInternal
Creating resource group OgreAutodetect
SceneManagerFactory for type 'DefaultSceneManager' registered.
Registering ResourceManager for type Material
Registering ResourceManager for type Mesh
Registering ResourceManager for type Skeleton
MovableObjectFactory for type 'ParticleSystem' registered.
ArchiveFactory for type 'FileSystem' registered
ArchiveFactory for type 'Zip' registered
ArchiveFactory for type 'EmbeddedZip' registered
DDS codec registering
ETC codec registering
ASTC codec registering
Registering ResourceManager for type GpuProgram
Registering ResourceManager for type Compositor
MovableObjectFactory for type 'Entity' registered.
MovableObjectFactory for type 'Light' registered.
MovableObjectFactory for type 'BillboardSet' registered.
MovableObjectFactory for type 'ManualObject' registered.
MovableObjectFactory for type 'BillboardChain' registered.
MovableObjectFactory for type 'RibbonTrail' registered.
MovableObjectFactory for type 'StaticGeometry' registered.
MovableObjectFactory for type 'Rectangle2D' registered.
*-*-* OGRE Initialising
*-*-* Version 13.3.0 (Tsathoggua)
::: Time Init main:  19 ms
System: Linux
Paths info
-------------------------
Ogre plugin:  /snap/stuntrally/110/usr/lib/OGRE/
Data:         /snap/stuntrally/110/usr/share/games/stuntrally
Home:         /root/snap/stuntrally/110
User cfg,log: /root/snap/stuntrally/110/.config/stuntrally
User data:    /root/snap/stuntrally/110/.local/share/stuntrally
Cache:        /root/snap/stuntrally/common/.cache/stuntrally
-------------------------
@  ---- Sound devices ----
No protocol specified
xcb_connection_has_error() returned true
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL hw:0
AL lib: (EE) probe_devices: control open (hw:0): No such file or directory
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL hw:1
AL lib: (EE) probe_devices: control open (hw:1): No such file or directory
@  ALSA Default
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
@@@  Sound Init - Could not open device
))  OpenAL Error: (null) (0xa004), @ /build/stuntrally/parts/stuntrally/src/source/sound/SoundBaseMgr.cpp:66
@  SoundScript: Failed to create Sound Manager
@  SoundScript: Parsing
@  SoundScript: Parsed: 44 templates.
::: Time Sounds:  35 ms
@  Sound init - Disabled.
*** start setup ***
Loading library /snap/stuntrally/110/usr/lib/OGRE//RenderSystem_GL.so.13.3
Installing plugin: GL RenderSystem
OpenGL Rendering Subsystem created.
No protocol specified
EGL: using default display. Device extensions: EGL_EXT_device_drm
/usr/share/libdrm/amdgpu.ids: No such file or directory
No protocol specified
Plugin successfully installed
Loading library /snap/stuntrally/110/usr/lib/OGRE//Plugin_ParticleFX.so.13.3
Installing plugin: ParticleFX
Particle Emitter Type 'Point' registered
Particle Emitter Type 'Box' registered
Particle Emitter Type 'Ellipsoid' registered
Particle Emitter Type 'Cylinder' registered
Particle Emitter Type 'Ring' registered
Particle Emitter Type 'HollowEllipsoid' registered
Particle Affector Type 'LinearForce' registered
Particle Affector Type 'ColourFader' registered
Particle Affector Type 'ColourFader2' registered
Particle Affector Type 'ColourImage' registered
Particle Affector Type 'ColourInterpolator' registered
Particle Affector Type 'Scaler' registered
Particle Affector Type 'Rotator' registered
Particle Affector Type 'DirectionRandomiser' registered
Particle Affector Type 'DeflectorPlane' registered
Particle Affector Type 'TextureAnimator' registered
Plugin successfully installed
Loading library /snap/stuntrally/110/usr/lib/OGRE//Codec_STBI.so.13.3
stb_image - v2.27 - public domain image loader
Supported formats: jpeg,jpg,png,bmp,psd,tga,gif,pic,ppm,pgm,hdr
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/loading' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/fonts' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/gui' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/hud' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/materials2' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/road' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/grass' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/skies' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/terrain' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/trees-old' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/trees' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/trees2' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/particles' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/objects' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/objects0' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/objectsC' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/tracks/_previews' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/cars/_previews' of type 'FileSystem' to resource group 'General'
CPU Identifier & Features
-------------------------
 *   CPU ID: GenuineIntel: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
 *          SSE: yes
 *         SSE2: yes
 *         SSE3: yes
 *        SSE41: yes
 *        SSE42: yes
 *          MMX: yes
 *       MMXEXT: yes
 *        3DNOW: no
 *     3DNOWEXT: no
 *         CMOV: yes
 *          TSC: yes
 *INVARIANT TSC: yes
 *          FPU: yes
 *          PRO: yes
 *           HT: no
-------------------------
******************************
*** Starting EGL Subsystem ***
******************************
EGL_VENDOR = Mesa Project
EGL_VERSION = 1.5
EGL_EXTENSIONS = EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_wayland EGL_EXT_platform_x11 EGL_MESA_platform_gbm EGL_MESA_platform_surfaceless EGL_EXT_platform_device EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver 
Registering ResourceManager for type Texture
No protocol specified
Segmentation fault
root@debian:/home/ch/dn# exit
exit
ch@debian:~/dn$ snap run stuntrally
Creating resource group General
Creating resource group OgreInternal
Creating resource group OgreAutodetect
SceneManagerFactory for type 'DefaultSceneManager' registered.
Registering ResourceManager for type Material
Registering ResourceManager for type Mesh
Registering ResourceManager for type Skeleton
MovableObjectFactory for type 'ParticleSystem' registered.
ArchiveFactory for type 'FileSystem' registered
ArchiveFactory for type 'Zip' registered
ArchiveFactory for type 'EmbeddedZip' registered
DDS codec registering
ETC codec registering
ASTC codec registering
Registering ResourceManager for type GpuProgram
Registering ResourceManager for type Compositor
MovableObjectFactory for type 'Entity' registered.
MovableObjectFactory for type 'Light' registered.
MovableObjectFactory for type 'BillboardSet' registered.
MovableObjectFactory for type 'ManualObject' registered.
MovableObjectFactory for type 'BillboardChain' registered.
MovableObjectFactory for type 'RibbonTrail' registered.
MovableObjectFactory for type 'StaticGeometry' registered.
MovableObjectFactory for type 'Rectangle2D' registered.
*-*-* OGRE Initialising
*-*-* Version 13.3.0 (Tsathoggua)
::: Time Init main:   4 ms
System: Linux
Paths info
-------------------------
Ogre plugin:  /snap/stuntrally/110/usr/lib/OGRE/
Data:         /snap/stuntrally/110/usr/share/games/stuntrally
Home:         /home/ch/snap/stuntrally/110
User cfg,log: /home/ch/snap/stuntrally/110/.config/stuntrally
User data:    /home/ch/snap/stuntrally/110/.local/share/stuntrally
Cache:        /home/ch/snap/stuntrally/common/.cache/stuntrally
-------------------------
@  ---- Sound devices ----
@  USB HIFI Audio Analog Stereo
@  EFX extension found.
@ @  ---- SoundManager Info ----
@  vendor: OpenAL Community
@  version: 1.1 ALSOFT 1.18.2
@  renderer: OpenAL Soft
@  extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
@  Aux Sends per Source: 4
@  SoundScript: Sound Manager started with 0 sources
@  SoundScript: Parsing
@  SoundScript: Parsed: 44 templates.
::: Time Sounds:  12 ms
@  Sound init ok.
*** start setup ***
Loading library /snap/stuntrally/110/usr/lib/OGRE//RenderSystem_GL.so.13.3
Installing plugin: GL RenderSystem
OpenGL Rendering Subsystem created.
/usr/share/libdrm/amdgpu.ids: No such file or directory
Plugin successfully installed
Loading library /snap/stuntrally/110/usr/lib/OGRE//Plugin_ParticleFX.so.13.3
Installing plugin: ParticleFX
Particle Emitter Type 'Point' registered
Particle Emitter Type 'Box' registered
Particle Emitter Type 'Ellipsoid' registered
Particle Emitter Type 'Cylinder' registered
Particle Emitter Type 'Ring' registered
Particle Emitter Type 'HollowEllipsoid' registered
Particle Affector Type 'LinearForce' registered
Particle Affector Type 'ColourFader' registered
Particle Affector Type 'ColourFader2' registered
Particle Affector Type 'ColourImage' registered
Particle Affector Type 'ColourInterpolator' registered
Particle Affector Type 'Scaler' registered
Particle Affector Type 'Rotator' registered
Particle Affector Type 'DirectionRandomiser' registered
Particle Affector Type 'DeflectorPlane' registered
Particle Affector Type 'TextureAnimator' registered
Plugin successfully installed
Loading library /snap/stuntrally/110/usr/lib/OGRE//Codec_STBI.so.13.3
stb_image - v2.27 - public domain image loader
Supported formats: jpeg,jpg,png,bmp,psd,tga,gif,pic,ppm,pgm,hdr
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/loading' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/fonts' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/gui' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/hud' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/materials2' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/road' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/grass' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/skies' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/terrain' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/trees-old' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/trees' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/trees2' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/particles' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/objects' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/objects0' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/objectsC' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/tracks/_previews' of type 'FileSystem' to resource group 'General'
Added resource location '/snap/stuntrally/110/usr/share/games/stuntrally/cars/_previews' of type 'FileSystem' to resource group 'General'
CPU Identifier & Features
-------------------------
 *   CPU ID: GenuineIntel: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
 *          SSE: yes
 *         SSE2: yes
 *         SSE3: yes
 *        SSE41: yes
 *        SSE42: yes
 *          MMX: yes
 *       MMXEXT: yes
 *        3DNOW: no
 *     3DNOWEXT: no
 *         CMOV: yes
 *          TSC: yes
 *INVARIANT TSC: yes
 *          FPU: yes
 *          PRO: yes
 *           HT: no
-------------------------
******************************
*** Starting EGL Subsystem ***
******************************
EGL_VENDOR = Mesa Project
EGL_VERSION = 1.5
EGL_EXTENSIONS = EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_wayland EGL_EXT_platform_x11 EGL_MESA_platform_gbm EGL_MESA_platform_surfaceless EGL_EXT_platform_device EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_CHROMIUM_sync_control EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_NOK_texture_from_pixmap EGL_WL_bind_wayland_display 
Registering ResourceManager for type Texture
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not initialize SDL! Could not initialize UDEV
Aborted
```

**Comment by paroj** [comment]
probably it lacks some permissions, try:
```
snap connect stuntrally:home :home 
snap connect stuntrally:opengl :opengl 
snap connect stuntrally:x11 :x11 
snap connect stuntrally:pulseaudio :pulseaudio 
```
there is also `:joystick`, `:network`, `:network-bind`

If that does not help, you can try disabling the sandbox altogether:
```
snap remove stuntrally
snap install stuntrally --edge --devmode
```

**Comment by cryham** [comment]
Right then. I've reinstalled snap and stuntrally even and it somehow started working.
It works smooth. But I see few bugs:
- crash on screenshot, well it nicely quits when I press F12
- MyGui text RGB is BGR, colors are switched in MyGui texts everywhere, on HUD, lists, etc.:

How do I start SR editor?

**Comment by paroj** [comment]
didnt even notice the BGR thing. This is a MyGUI issue however: https://github.com/MyGUI/mygui/issues/230
Will try to rebuild the snap with MyGUI master. Lets hope it does not break other stuff.
Anyway, the idea of this PR is to allow building against Ogre 13, so someone else can take care of the remaining fallout.

As for the editor:
```sh
snap run stuntrally.editor
# or just
stuntrally.editor
```

**Comment by cryham** [comment]
Is this keeping 1.9 compatibility? Will it still be possible to build with Ogre 1.9 on Debian based?

**Comment by paroj** [comment]
yes, this is still 1.9 compatible. Bullseye is at Ogre 1.12 though.

**Comment by cryham** [comment]
Ok, I'm merging then.
Ah good to know. So the days are gone when I could just apt get ogre, build on Debian and play really easily. I guess the old Windows installer is only still working now.

**Comment by paroj** [comment]
not yet. There are both ogre-1.9 and ogre-1.12 packages.

**Pull request merged**
